### ISSUE TITLE
bugz

### ISSUE THREAD

**Issue by gpl666** [danieleServadei/python-patternGenerator#1]
1. se chiedo un pattern casuale ed indico per esempio di volere un pattern da 7 mi dà un pattern a caso minore od uguale a 7 caselle
2. Se faccio la ricerca di un pattern specifico secondo parametri, mi chiede di inserire i valori per "s" e "n", senza definire cosa siano (sarebbe meglio mi dicesse direttamente "lunghezza pattern" e "numero di pieni")
3. se faccio la ricerca di un pattern specifico il messaggio con le indicazioni sulle possibilità mi dice "naturalmente il valore s deve essere minore o uguale di [numero indicato dall'utente] e maggiore o uguale a 3/naturalmente il valore di n deve essere minore o uguale di [numero inserito dall'utente +1] e maggiore uguale a 0", ma il numero di "pieni" non può certamente superare il numero indicato dall'utente, e inoltre il valore di "s" è già stato inserito precedentemente. Inoltre se modifico questo valore poi posso inserire n>s generando un output nullo

**Comment by danieleServadei** [comment]
1. Il programma richiede il numero passimo che deve avere il pattern, e ne genera uno casuale compreso tra essi, è stato fatto apposta perchè mettendo un random da 3 a 33, in caso fosse capitato un numero alto, il programma ci avrebbe messo troppo a caricare. In breve vuole che richiedendo la lunghezza del pattern, generi un pattern casuale con numero di pieni e numero della soluzione casuale?
2. Fatto
3. s non viene richiesto sopra, viene solo richiesto tramite quale si vuole cercare, e poi richiede se si vuole fare una ricerca specifica. Il risultato viene nullo se l'utente inserisce un pattern non presente.. Dsi potrebbe inserire un error handling anche per quello.

**Comment by gpl666** [comment]
1. non ho ben capito la motivazione, comunque sì: intendevo che se scelgo l'opzione 2, cioè "genera e visualizza un pattern random", e poi inserisco un numero (es: 12), voglio che il software mi restituisca un pattern random di quella lunghezza (es: 12) [se vuoi sarebbe meglio poi che nell'opzione 2 comparisse "quanti caratteri deve avere il pattern" al singolare, visto che ne sto richiedendo uno]
2. 🌈
3. freghiamocene

**Comment by danieleServadei** [comment]
Già fatto 👍
Abbiamo integrato entrambe le opzioni

**Comment by gpl666** [comment]
Meraviglia <3
