### ISSUE TITLE
altro bug

### ISSUE THREAD

**Issue by gpl666** [danieleServadei/python-patternGenerator#2]
generando pattern particolarmente lunghi i tempi sono molto dilatati, e quindi non può stare a rigenerare l'elenco ogni volta:

se per esempio devo generare un pattern random da 31 caselle è certamente opportuno fargli generare solo un pattern casuale da 31 caselle direttamente

se invece devo generare diversi pattern tra cui attingere è certamente meglio fargli generare solo quelli della lunghezza indicata anzichè tutto l'elenco con anche i pattern più corti

l'elenco completo è conveniente venga generato esclusivamente nel caso l'utente voglia la disponibilità completa di tale elenco, ed è quindi opportuno che le intenzioni dell'utente siano note all'algoritmo prima che parta con il calcolo effettivo

**Comment by danieleServadei** [comment]
In breve, aggiungere altre funzioni per le possibilità di generazione random:
la prima, richiede tra 3 e x e genera un parametro random tra essi, dando un N ed I random
la seconda, richiede la lunghezza del pattern e genera esclusivamente un risultato random di quella lunghezza del pattern, con N ed I casuale

**Comment by danieleServadei** [comment]
Aggiunta

**Comment by gpl666** [comment]
non proprio; per snellire il processo:
1- il programma deve prima capire se vuoi azioni su un elenco completo o ti servono solo pattern di lunghezza specifica/un pattern singolo casuale di una lunghezza specifica e-o secondo parametri indicati dall'utente/un pattern o gruppo di pattern con un dato numero di pieni (n);
2- se l'utente vuole libertà sull'elenco completo il programma chiede fino a che lunghezza di pattern (s) deve arrivare a generare l'elenco;
3- se l'utente vuole solo lavorare sui pattern per esempio da 13 (a prescindere che mi interessi anche n, es: voglio un pattern da s=13 a caso, ma poi voglio poterne scegliere altri sempre con s=13 e a caso senza rischio di ripetizioni, o voglio scorrere da lì in avanti o indietro) il programma deve generare solo l'elenco dei pattern da 13 e agire su quel singolo elenco;
4- se l'utente vuole solo un pattern a caso, e il numero di slot inserito dall'utente e/o il numero di pieni è alto (valuta tu quand'è che diventa lunghetto a calcolare), anzichè calcolare tutto il gruppo e poi scegliere il casuale (es: utente inserisce s=32, programma calcola tutto il gruppo mettendoci 2 ere geologiche e poi seleziona una voce a caso e te la mostra) gli fai generare direttamente un singolo pattern a caso di quella lunghezza e/o numero di pieni; in questo caso non può ovviamente scorrere nè usufruire dello shuffle, ma solo del random (sacrificio necessario e consentito se generare tutto l'elenco per esempio da s=32 richiede un tempo indegnamente alto);

Nel caso 1, valuta la possibilità di far creare al programma un file permanente con l'elenco, in modo che poi non debba rigenerarlo ad ogni apertura del software, e in modo che se un giorno ho calcolato fino a 21 e il giorno dopo calcolo fino a 17 possa attingere direttamente dall'elenco che arriva a 21 [posto che non so se sia una richiesta adeguata al livello della vostra preparazione]
