### ISSUE TITLE
feature richiesta

### ISSUE THREAD

**Issue by gpl666** [danieleServadei/python-patternGenerator#3]
quando si chiede la generazione di un pattern casuale di sX caselle, una volta restituito il risultato, ci vorrebbe un "premere 1 per generarne un altro o invio per fa ripartire il programma", in modo che uno non debba rifare tutto da capo se vuole un po' di pattern da sX caselle di fila

**Comment by danieleServadei** [comment]
Feature aggiunta :D

**Comment by gpl666** [comment]
Grazie mille <3
